import { isAbsolute, relative, resolve } from "node:path";
import { canonicalExistingRoot, resolveExistingChild } from "@anastom/path-policy";
import Ajv, { type ErrorObject } from "ajv";
import { parse } from "yaml";

import featureDocumentSchema from "../schemas/feature-document.v1alpha1.json" with { type: "json" };
import { canonicalJson, digestJson } from "./canonical.js";
import { readBoundedUtf8 } from "./local-file.js";
import type {
  AttemptBudget,
  AttemptPolicyDocument,
  CommandDefinition,
  CommandDocument,
} from "./types.js";

const MAX_FEATURE_BYTES = 256 * 1024;
const MAX_OBJECTIVE_CHARACTERS = 65_536;
const DEFAULT_ATTEMPT_DURATION_MS = 20 * 60 * 1_000;
const ajv = new Ajv({ allErrors: true });

/** A deterministic verifier selected by the operator rather than generated by a model. */
interface FeatureVerifierDocument extends CommandDocument {
  id: string;
}

/**
 * Strict Feature front matter plus its Markdown objective.
 * @public
 */
export interface FeatureDocument {
  apiVersion: "anastom.dev/v1alpha1";
  kind: "Feature";
  metadata: { id: string; version: string };
  acceptanceCriteria: string[];
  verification: FeatureVerifierDocument[];
  policies?: {
    maxTasks?: number;
    maxParallel?: number;
    attemptPolicy?: AttemptPolicyDocument;
  };
  objective: string;
}

/** A normalized named verifier command ready for shell-free execution. */
export interface FeatureVerifierDefinition {
  id: string;
  command: CommandDefinition;
}

/** Persisted bounds that constrain planner output and implementation attempts. */
export interface FeaturePolicies {
  maxTasks: number;
  maxParallel: number;
  attemptBudget: AttemptBudget;
}

/** An immutable normalized Feature snapshot used to plan and verify one run. */
export interface FeatureDefinition {
  apiVersion: "anastom.dev/v1alpha1";
  kind: "Feature";
  metadata: { id: string; version: string };
  sourcePath: string;
  objective: string;
  acceptanceCriteria: readonly string[];
  verification: readonly FeatureVerifierDefinition[];
  policies: FeaturePolicies;
  documentDigest: string;
}

/**
 * Classified validation failure for Feature, methodology, plan, and review contracts.
 * @public
 */
export class SdlcValidationError extends Error {
  readonly issues: readonly string[];

  /** Collect contract violations into one operator-readable error. */
  constructor(subject: string, issues: readonly string[]) {
    super(`Invalid ${subject}:\n${issues.map((issue) => `- ${issue}`).join("\n")}`);
    this.name = "SdlcValidationError";
    this.issues = issues;
  }
}

type FeatureFrontMatter = Omit<FeatureDocument, "objective">;

const validateFeatureFrontMatter = ajv.compile<FeatureFrontMatter>(featureDocumentSchema);

/** Convert AJV diagnostics into stable field-oriented messages. */
export function formatSchemaErrors(errors: ErrorObject[] | null | undefined): string[] {
  return (errors ?? []).map((error) => {
    const location = error.instancePath.length > 0 ? error.instancePath : "/";
    const property =
      error.keyword === "additionalProperties"
        ? ` (${String(error.params.additionalProperty)})`
        : "";
    return `${location} ${error.message ?? "is invalid"}${property}`;
  });
}

function splitFrontMatter(source: string): { yaml: string; body: string } {
  const text = source.startsWith("\uFEFF") ? source.slice(1) : source;
  const lines = text.split(/(?<=\n)/);
  if (lines.length === 0 || lines[0]?.replace(/\r?\n$/, "") !== "---") {
    throw new SdlcValidationError("Feature", [
      "Feature requires YAML front matter and a Markdown objective",
    ]);
  }
  let offset = lines[0]?.length ?? 0;
  for (let index = 1; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    if (line.replace(/\r?\n$/, "") === "---") {
      return {
        yaml: text.slice(lines[0]?.length ?? 0, offset),
        body: text.slice(offset + line.length),
      };
    }
    offset += line.length;
  }
  throw new SdlcValidationError("Feature", [
    "Feature requires YAML front matter and a Markdown objective",
  ]);
}

function durationToMilliseconds(duration: string | undefined): number {
  const selected = duration ?? "20m";
  const match = /^(\d+)(ms|s|m|h)$/.exec(selected);
  if (match === null) {
    throw new SdlcValidationError("Feature", [`invalid duration ${JSON.stringify(selected)}`]);
  }
  const multipliers: Record<string, number> = { ms: 1, s: 1_000, m: 60_000, h: 3_600_000 };
  const milliseconds = Number(match[1]) * multipliers[match[2] ?? ""]!;
  if (!Number.isSafeInteger(milliseconds) || milliseconds > 2_147_483_647) {
    throw new SdlcValidationError("Feature", ["duration exceeds supported timer range"]);
  }
  return milliseconds;
}

function normalizeVerifier(verifier: FeatureVerifierDocument): FeatureVerifierDefinition {
  const cwd = verifier.cwd ?? ".";
  if (isAbsolute(cwd) || cwd.includes("\\") || cwd.split("/").includes("..")) {
    throw new SdlcValidationError("Feature", [
      `/verification/${verifier.id}/cwd must stay within the workspace`,
    ]);
  }
  return {
    id: verifier.id,
    command: {
      argv: [...verifier.argv],
      cwd,
      maxDurationMs: durationToMilliseconds(verifier.maxDuration),
      maxOutputBytes: verifier.maxOutputBytes ?? 1_048_576,
    },
  };
}

/**
 * Parse strict YAML front matter and preserve the nonempty Markdown objective.
 * @public
 */
export function parseFeatureMarkdown(source: string): FeatureDocument {
  const { yaml, body } = splitFrontMatter(source);
  let candidate: unknown;
  try {
    candidate = parse(yaml);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new SdlcValidationError("Feature", [`YAML parse error: ${message}`]);
  }
  if (!validateFeatureFrontMatter(candidate)) {
    throw new SdlcValidationError("Feature", formatSchemaErrors(validateFeatureFrontMatter.errors));
  }
  const objective = body.trim();
  if (objective.length === 0) {
    throw new SdlcValidationError("Feature", ["Feature objective must not be empty"]);
  }
  if (objective.length > MAX_OBJECTIVE_CHARACTERS) {
    throw new SdlcValidationError("Feature", ["Feature objective exceeds 65536 characters"]);
  }
  const verifierIds = candidate.verification.map(({ id }) => id);
  if (new Set(verifierIds).size !== verifierIds.length) {
    throw new SdlcValidationError("Feature", ["verification IDs must be unique"]);
  }
  if (
    candidate.policies?.maxParallel !== undefined &&
    candidate.policies.maxTasks !== undefined &&
    candidate.policies.maxParallel > candidate.policies.maxTasks
  ) {
    throw new SdlcValidationError("Feature", ["maxParallel cannot exceed maxTasks"]);
  }
  return { ...candidate, objective };
}

/**
 * Normalize a parsed Feature into the exact contract persisted with a run.
 * @public
 */
export function normalizeFeature(document: FeatureDocument, sourcePath: string): FeatureDefinition {
  const policies: FeaturePolicies = {
    maxTasks: document.policies?.maxTasks ?? 8,
    maxParallel: document.policies?.maxParallel ?? 2,
    attemptBudget: {
      maxAttempts: document.policies?.attemptPolicy?.maxAttempts ?? 1,
      maxDurationMs:
        document.policies?.attemptPolicy?.maxDuration === undefined
          ? DEFAULT_ATTEMPT_DURATION_MS
          : durationToMilliseconds(document.policies.attemptPolicy.maxDuration),
    },
  };
  const normalized = {
    apiVersion: document.apiVersion,
    kind: document.kind,
    metadata: { ...document.metadata },
    objective: document.objective,
    acceptanceCriteria: [...document.acceptanceCriteria],
    verification: document.verification.map(normalizeVerifier),
    policies,
  } as const;
  return {
    ...normalized,
    sourcePath: resolve(sourcePath),
    documentDigest: digestJson(normalized),
  };
}

/**
 * Validate an immutable normalized Feature loaded from durable storage.
 * @throws SdlcValidationError when fields, normalization, or the content digest disagree.
 * @public
 */
export function assertFeatureDefinition(value: unknown): asserts value is FeatureDefinition {
  if (
    value === null ||
    typeof value !== "object" ||
    !("sourcePath" in value) ||
    typeof value.sourcePath !== "string" ||
    !("policies" in value) ||
    value.policies === null ||
    typeof value.policies !== "object" ||
    !("attemptBudget" in value.policies) ||
    value.policies.attemptBudget === null ||
    typeof value.policies.attemptBudget !== "object"
  ) {
    throw new SdlcValidationError("Feature definition", ["normalized shape is invalid"]);
  }
  const feature = value as FeatureDefinition;
  let normalized: FeatureDefinition;
  try {
    normalized = normalizeFeature(
      {
        apiVersion: feature.apiVersion,
        kind: feature.kind,
        metadata: structuredClone(feature.metadata),
        acceptanceCriteria: [...feature.acceptanceCriteria],
        verification: feature.verification.map(({ id, command }) => ({
          id,
          argv: [...command.argv],
          cwd: command.cwd,
          maxDuration: `${command.maxDurationMs}ms`,
          maxOutputBytes: command.maxOutputBytes,
        })),
        policies: {
          maxTasks: feature.policies.maxTasks,
          maxParallel: feature.policies.maxParallel,
          attemptPolicy: {
            maxAttempts: feature.policies.attemptBudget.maxAttempts,
            maxDuration: `${feature.policies.attemptBudget.maxDurationMs}ms`,
          },
        },
        objective: feature.objective,
      },
      feature.sourcePath,
    );
  } catch (error) {
    if (error instanceof SdlcValidationError) {
      throw error;
    }
    throw new SdlcValidationError("Feature definition", ["normalized shape is invalid"]);
  }
  if (canonicalJson(normalized) !== canonicalJson(feature)) {
    throw new SdlcValidationError("Feature definition", [
      "normalized content or digest does not match",
    ]);
  }
}

/**
 * Load and normalize a Feature selected beneath one caller-authorized source root.
 * @public
 */
export async function loadFeatureWithinRoot(
  rootPath: string,
  filePath: string,
): Promise<FeatureDefinition> {
  const root = await canonicalExistingRoot(rootPath);
  const selected = relative(resolve(rootPath), resolve(rootPath, filePath));
  const sourcePath = await resolveExistingChild(root, selected, "file");
  const source = await readBoundedUtf8(sourcePath, {
    maxBytes: MAX_FEATURE_BYTES,
    label: "Feature document",
  });
  return normalizeFeature(parseFeatureMarkdown(source), sourcePath);
}
